#Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: vulnerable
---
#Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role
  namespace: vulnerable
rules:
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - '*'
---
#RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding
  namespace: vulnerable
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: attacker
---
#ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: attacker
  namespace: vulnerable
---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deploy
  name: nginx-deploy
  namespace: vulnerable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deploy
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec:
      serviceAccountName: attacker
      containers:
      - image: nginx
        name: nginx
---
#Service
apiVersionService: v1
kind: Service
metadata:
  labels:
    app: nginx-deploy
  name: nginx-deploy-service
  namespace: vulnerable
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: nginx-deploy
  type: NodePort
status:
  loadBalancer: {}
